serverapi:
  serverconfig:
    #Quand le devmode est activé, la condition de victoire est désactivée.  devmode: false/true
    devmode: false
    #Indique le code discord affiché dans le tab.
    DiscordLink: "xxxxx"
    #Indique l'ip du serveur, dans le tab et dans le scoreboard
    ServerId: "xxxx.xxxx"
    #Indique le nom du serveur
    servername: "SERVER"
    #Active la whitelist par défaut. whitelist: false/true
    whitelist: false
    #Indique le liens vers lequel renvoie la commande /docs
    doc_url: "google.com"
  #Toutes les coordonnées doivent être entières. Pas de chiffre à virgule.
  #
  #Coordonnée du spawn
  spawn:
    x: 0
    y: 41
    z: 0
  #Coordonnée de la salle des règles.
  ruleroom:
    x: 0
    y: 41
    z: 0
  #Coordonnée de la boite à host.
  hostbox:
    x: 0
    y: 41
    z: 0
  #Ne pas modifié.
  stuff:
    actualconfig: ""