serverapi:
  serverconfig:
    #Quand le devmode est activé, la condition de victoire est désactivée.  devmode: false/true
    devmode: false
    #Indique le code discord affiché dans le tab.
    DiscordLink: "xxxxx"
    #Indique l'ip du serveur, dans le tab et dans le scoreboard
    ServerId: "xxxx.xxxx"
    #Indique le nom du serveur
    servername: "SERVER"
    #Active la whitelist par défaut. whitelist: false/true
    whitelist: false
    #Indique le liens vers lequel renvoie la commande /docs
    doc_url: "google.com"
    #Indique si un joueur qui est op peut changer l'host même si il ne l'est pas lui même.
    op_host_bypass: false
  #Toutes les coordonnées doivent être entières. Pas de chiffre à virgule.
  #
  #Coordonnée du spawn
  spawn:
    x: 0
    y: 41
    z: 0
  #Coordonnée de la salle des règles.
  ruleroom:
    x: 0
    y: 41
    z: 0
  #Coordonnée de la boite à host.
  hostbox:
    x: 0
    y: 41
    z: 0
  permissions:
    #Voici les configurations pour les permissions de l'host et des cohosts
    #Pour mettre toute les permissions: "all"
    #Permissions disponible:
    # Allow_bypass: permet au joueur de se bypass
    # Allow_config: permet au joueur de changer la configuration de la partie avec la commande /menu
    # Allow_hsay: permet au joueur d'envoyer des messages en tant qu'hote de la partie
    # Allow_add_whitelist: permet au joueur d'ajouter d'autres joueurs à la whitelist
    # Allow_koff: permet au joueur de tuer un joueur hors-ligne
    # Allow_groups_message: permet au joueur d'envoyer l'avertissement de groupe
    # Allow_change_game_name: permet au joueur de changer le nom de la partie
    # Allow_force: permet au joueur de forcer les timers: role, bordure, pvp
    # Allow_finalheal: permet au joueur d'effectuer un finalheal
    # See_helpop: permet au joueur de voir les messages de helpop
    host: "all"
    cohost: [Allow_config,Allow_hsay,Allow_groups_message,Allow_add_whitelist,Allow_finalheal,See_helpop]
    #Si il y a une erreur dans l'écriture des permissions. Les permissions de l'hôte et des cohosts seront au maximum.